const assetPath = (name) => `${import.meta.env.BASE_URL}assets/${name}`;
const appAssetIcon = (name, extension = "svg") =>
  assetPath(`app-icons/${name}.${extension}`);

export const appCategories = [
  { id: "discover", label: { zh: "发现", en: "Discover" }, icon: "radar" },
  { id: "creativity", label: { zh: "创作", en: "Creativity" }, icon: "draw" },
  { id: "productivity", label: { zh: "效率", en: "Productivity" }, icon: "work" },
  { id: "developer", label: { zh: "开发工具", en: "Developer Tools" }, icon: "terminal" },
  { id: "fun", label: { zh: "娱乐", en: "Fun" }, icon: "spark" },
  { id: "lifestyle", label: { zh: "生活方式", en: "Lifestyle" }, icon: "leaf" },
  { id: "utilities", label: { zh: "实用工具", en: "Utilities" }, icon: "extension" },
  { id: "ai", label: { zh: "AI", en: "AI" }, icon: "brain" },
];

export const appMarketCopy = {
  zh: {
    brand: "应用市场",
    marketKicker: "青焰Hub App Market",
    marketTitle: "应用市场",
    marketLead:
      "统一浏览青焰可安装应用、AI 工具、自动化工作流、版本历史和权限说明。适合从本地模型、Agent、创作工具到生产力应用的快速接入。",
    recommended: "查看推荐应用",
    orbitLabel: "应用市场摘要",
    orbitMeta: "真实应用图标 · 版本历史 · 权限透明 · 安装前确认资源",
    search: "搜索",
    categories: "分类",
    category: "分类",
    allCategories: "全部分类",
    view: "展示",
    viewAria: "切换展示方式",
    grid: "图块",
    list: "列表",
    quickFilter: "应用分类快捷筛选",
    all: "全部",
    loadMore: "加载更多应用",
    allShown: "已展示全部",
    appsUnit: "个应用",
    discover: "发现",
    amazingApps: "发现精彩应用",
    searchPlaceholder: "搜索应用、分类或描述",
    communityChoices: "社区精选",
    topApps: "青焰热门应用",
    latestApps: "最新应用",
    seeAll: "查看全部",
    back: "返回应用市场",
    developer: "开发者",
    languageLabel: "语言",
    memory: "所需内存",
    disk: "所需磁盘",
    cpu: "所需 CPU",
    gpu: "所需 GPU",
    about: "应用介绍",
    screenshots: "应用截图",
    chartVersion: "Chart 版本",
    versionHistory: "历史版本",
    seeAllVersions: "查看所有版本",
    sourceCode: "源代码",
    public: "公开",
    requiredPermissions: "所需权限",
    get: "获取",
    install: "安装",
    compatible: "兼容青焰应用协议",
    versionHistoryTitle: "版本历史",
    released: "发布时间",
    changelog: "更新内容",
    current: "当前版本",
    allVersions: "全部版本",
  },
  en: {
    brand: "verdantflare Market",
    marketKicker: "verdantflare App Market",
    marketTitle: "App Market",
    marketLead:
      "Browse installable verdantflare apps, AI tools, automation workflows, version history, and permissions in one place. Built for local models, agents, creative tools, and productivity apps.",
    recommended: "View Recommended App",
    orbitLabel: "App market summary",
    orbitMeta: "Real app icons · Version history · Transparent permissions · Confirm resources before install",
    search: "Search",
    categories: "Categories",
    category: "Category",
    allCategories: "All Categories",
    view: "View",
    viewAria: "Switch display mode",
    grid: "Grid",
    list: "List",
    quickFilter: "App category quick filters",
    all: "All",
    loadMore: "Load More Apps",
    allShown: "Showing all",
    appsUnit: "apps",
    discover: "Discover",
    amazingApps: "Discover Amazing Apps",
    searchPlaceholder: "Search apps, categories, or descriptions",
    communityChoices: "Community choices",
    topApps: "Top apps on verdantflare",
    latestApps: "Latest apps on verdantflare",
    seeAll: "See all",
    back: "Back to Market",
    developer: "Developer",
    languageLabel: "Language",
    memory: "Required memory",
    disk: "Required disk",
    cpu: "Required CPU",
    gpu: "Required GPU",
    about: "About",
    screenshots: "Screenshots",
    chartVersion: "Chart version",
    versionHistory: "Version history",
    seeAllVersions: "See all versions",
    sourceCode: "Source code",
    public: "Public",
    requiredPermissions: "Required permissions",
    get: "Get",
    install: "Install",
    compatible: "Compatible with verdantflare app protocol",
    versionHistoryTitle: "Version history",
    released: "Released",
    changelog: "Changelog",
    current: "Current",
    allVersions: "All versions",
  },
};

export const topicCards = [
  {
    label: "GET STARTED",
    title: "Unleash Your Creativity!",
    subtitle: "Paints Like a Pro with Stable Diffusion on verdantflare",
    image: assetPath("usecase-ad-storyboard.webp"),
  },
  {
    label: "GET STARTED",
    title: "Never Miss Your Ideas",
    subtitle: "Effortless Knowledge Management on verdantflare",
    image: assetPath("usecase-script-video.webp"),
  },
  {
    label: "FEATURED APP",
    title: "Game On the Go",
    subtitle: "Play Your Steam Games Anywhere, On Any Device",
    image: assetPath("usecase-previz-room.webp"),
  },
  {
    label: "FEATURED APP",
    title: "From Inspiration to Melody",
    subtitle: "Making Music with ACE-Step",
    image: assetPath("usecase-ecommerce.webp"),
  },
];

export const marketApps = [
  {
    id: "ollama",
    name: "Ollama",
    summary: "Get up and running with large language models.",
    category: "ai",
    developer: "Ollama",
    language: "EN",
    languageName: "English",
    icon: appAssetIcon("ollama"),
    hero: assetPath("usecase-script-video.webp"),
    version: "1.0.23",
    source: "Public",
    stats: { memory: "8 GB", disk: "12 GB", cpu: "4 Core", gpu: "Optional" },
    permissions: ["drive_file_move", "network_proxy", "settings_system"],
    description:
      "Run open models locally and expose an internal API for other AI apps in your personal cloud.",
    screenshots: [
      assetPath("usecase-script-video.webp"),
      assetPath("usecase-ad-storyboard.webp"),
    ],
    versions: [
      { version: "1.0.23", date: "2026-07-02", notes: "Updated runtime image and model storage checks." },
      { version: "1.0.18", date: "2026-05-19", notes: "Improved service discovery for internal API clients." },
      { version: "1.0.12", date: "2026-03-08", notes: "Added GPU scheduling hints and health probes." },
    ],
  },
  {
    id: "openwebui",
    name: "Open WebUI",
    summary: "User-friendly WebUI for LLMs",
    category: "ai",
    developer: "青焰Hub",
    language: "EN",
    languageName: "English",
    icon: appAssetIcon("open-webui"),
    hero: assetPath("usecase-script-video.webp"),
    version: "1.0.16",
    source: "Public",
    stats: { memory: "2 GB", disk: "4 GB", cpu: "2 Core", gpu: "-" },
    permissions: ["network_proxy", "user_profile", "secret_read"],
    description:
      "A polished web interface for local and private LLM workflows, including chat, prompts, files, and model routing.",
    screenshots: [assetPath("usecase-script-video.webp")],
    versions: [
      { version: "1.0.16", date: "2026-06-22", notes: "Refreshed WebUI image and fixed entrance labels." },
      { version: "1.0.11", date: "2026-04-14", notes: "Added shared-service configuration examples." },
    ],
  },
  {
    id: "openclaw",
    name: "OpenClaw",
    summary: "Personal AI Assistant with Multi-channel Inbox Support",
    category: "ai",
    developer: "OpenClaw",
    language: "EN",
    languageName: "English",
    icon: appAssetIcon("openclaw"),
    hero: assetPath("usecase-previz-room.webp"),
    version: "1.0.9",
    source: "Public",
    stats: { memory: "4 GB", disk: "8 GB", cpu: "2 Core", gpu: "Optional" },
    permissions: ["network_proxy", "user_profile", "drive_file_move"],
    description:
      "A personal AI assistant that connects model backends, inboxes, and task workflows into one agent surface.",
    screenshots: [assetPath("usecase-previz-room.webp")],
    versions: [
      { version: "1.0.9", date: "2026-06-28", notes: "Added channel routing and assistant workspace updates." },
      { version: "1.0.4", date: "2026-04-18", notes: "Improved inbox connector setup." },
    ],
  },
  {
    id: "affine",
    name: "AFFiNE",
    summary: "Open-source alternative for Notion, Miro and Airtable.",
    category: "productivity",
    developer: "青焰Hub",
    language: "EN",
    languageName: "English",
    icon: appAssetIcon("affine"),
    hero: assetPath("usecase-previz-room.webp"),
    version: "1.0.18",
    source: "Public",
    stats: { memory: "-", disk: "-", cpu: "-", gpu: "-" },
    permissions: ["drive_file_move", "dataset", "cache_read"],
    description:
      "A workspace for writing, whiteboarding, and structured knowledge management with local-first collaboration.",
    screenshots: [assetPath("usecase-previz-room.webp")],
    versions: [
      { version: "1.0.18", date: "2026-06-18", notes: "Updated chart metadata and data directory permissions." },
      { version: "1.0.12", date: "2026-04-03", notes: "Improved initialization and backup compatibility." },
      { version: "1.0.6", date: "2026-01-26", notes: "Initial public package for the app market." },
    ],
  },
  {
    id: "comfyui",
    name: "ComfyUI",
    summary: "The most powerful and modular stable diffusion GUI and backend.",
    category: "creativity",
    developer: "青焰Hub",
    language: "EN",
    languageName: "English",
    icon: appAssetIcon("comfyui"),
    hero: assetPath("usecase-ad-storyboard.webp"),
    version: "1.1.7",
    source: "Public",
    stats: { memory: "12 GB", disk: "20 GB", cpu: "4 Core", gpu: "Required" },
    permissions: ["drive_file_move", "gpu_schedule", "network_proxy"],
    description:
      "A shared image-generation backend for workflows, custom nodes, checkpoints, and creative pipelines.",
    screenshots: [assetPath("usecase-ad-storyboard.webp")],
    versions: [
      { version: "1.1.7", date: "2026-07-01", notes: "Added shared GPU queue and model mount updates." },
      { version: "1.1.1", date: "2026-05-05", notes: "Updated custom node bootstrap process." },
    ],
  },
  {
    id: "steamheadless",
    name: "Steam Headless",
    summary: "A Headless Steam Service",
    category: "fun",
    developer: "青焰Hub",
    language: "EN",
    languageName: "English",
    icon: appAssetIcon("steam"),
    hero: assetPath("usecase-previz-room.webp"),
    version: "1.0.9",
    source: "Public",
    stats: { memory: "8 GB", disk: "40 GB", cpu: "4 Core", gpu: "Required" },
    permissions: ["gpu_schedule", "display_stream", "network_proxy"],
    description:
      "Stream and manage a headless Steam instance from your private verdantflare environment.",
    screenshots: [assetPath("usecase-previz-room.webp")],
    versions: [
      { version: "1.0.9", date: "2026-05-30", notes: "Improved display startup and controller mapping." },
      { version: "1.0.5", date: "2026-03-20", notes: "Fixed storage mount detection." },
    ],
  },
  {
    id: "n8n",
    name: "n8n",
    summary: "n8n is an extendable workflow automation tool.",
    category: "developer",
    developer: "青焰Hub",
    language: "EN",
    languageName: "English",
    icon: appAssetIcon("n8n"),
    hero: assetPath("usecase-script-video.webp"),
    version: "1.0.14",
    source: "Public",
    stats: { memory: "2 GB", disk: "8 GB", cpu: "2 Core", gpu: "-" },
    permissions: ["network_proxy", "secret_read", "dataset"],
    description:
      "Build automation workflows that connect AI services, APIs, files, and internal app entrances.",
    screenshots: [assetPath("usecase-script-video.webp")],
    versions: [
      { version: "1.0.14", date: "2026-07-04", notes: "Updated node packages and webhook entrance handling." },
      { version: "1.0.9", date: "2026-05-16", notes: "Improved credential persistence." },
    ],
  },
  {
    id: "nocodb",
    name: "NocoDB",
    summary: "Open Source Airtable Alternative.",
    category: "productivity",
    developer: "青焰Hub",
    language: "EN",
    languageName: "English",
    icon: appAssetIcon("nocodb"),
    hero: assetPath("usecase-ecommerce.webp"),
    version: "1.0.10",
    source: "Public",
    stats: { memory: "2 GB", disk: "6 GB", cpu: "2 Core", gpu: "-" },
    permissions: ["dataset", "network_proxy", "drive_file_move"],
    description:
      "Turn databases into collaborative spreadsheets and internal tools without leaving your private cloud.",
    screenshots: [assetPath("usecase-ecommerce.webp")],
    versions: [
      { version: "1.0.10", date: "2026-06-09", notes: "Updated app image and database migration checks." },
      { version: "1.0.4", date: "2026-02-17", notes: "Initial marketplace package." },
    ],
  },
  {
    id: "bytebase",
    name: "Bytebase",
    summary: "World's most advanced database DevOps and CI/CD for Developer, DBA and Platform Engineering teams.",
    category: "developer",
    developer: "青焰Hub",
    language: "EN",
    languageName: "English",
    icon: appAssetIcon("bytebase", "png"),
    hero: assetPath("usecase-script-video.webp"),
    version: "1.0.8",
    source: "Public",
    stats: { memory: "2 GB", disk: "4 GB", cpu: "2 Core", gpu: "-" },
    permissions: ["network_proxy", "secret_read", "dataset"],
    description:
      "Manage database changes, approvals, environments, and audit trails from a self-hosted DevOps console.",
    screenshots: [assetPath("usecase-script-video.webp")],
    versions: [
      { version: "1.0.8", date: "2026-06-12", notes: "Updated database drivers and readiness probes." },
      { version: "1.0.3", date: "2026-03-11", notes: "Added backup volume configuration." },
    ],
  },
  {
    id: "jellyfin",
    name: "Jellyfin",
    summary: "The Free Software Media System",
    category: "lifestyle",
    developer: "青焰Hub",
    language: "EN",
    languageName: "English",
    icon: appAssetIcon("jellyfin"),
    hero: assetPath("usecase-previz-room.webp"),
    version: "1.0.11",
    source: "Public",
    stats: { memory: "2 GB", disk: "10 GB", cpu: "2 Core", gpu: "Optional" },
    permissions: ["drive_file_move", "media_library", "network_proxy"],
    description:
      "Host and stream your personal media library with private indexing, transcoding, and device playback.",
    screenshots: [assetPath("usecase-previz-room.webp")],
    versions: [
      { version: "1.0.11", date: "2026-05-27", notes: "Updated transcoding settings and library permissions." },
      { version: "1.0.6", date: "2026-02-02", notes: "Improved shared media volume defaults." },
    ],
  },
  {
    id: "vaultwarden",
    name: "Vaultwarden",
    summary: "Alternative Bitwarden compatible server written in Rust.",
    category: "utilities",
    developer: "青焰Hub",
    language: "EN",
    languageName: "English",
    icon: appAssetIcon("vaultwarden"),
    hero: assetPath("usecase-ecommerce.webp"),
    version: "1.0.7",
    source: "Public",
    stats: { memory: "512 MB", disk: "1 GB", cpu: "1 Core", gpu: "-" },
    permissions: ["secret_read", "network_proxy", "dataset"],
    description:
      "A lightweight password manager backend for private credential storage and browser/client syncing.",
    screenshots: [assetPath("usecase-ecommerce.webp")],
    versions: [
      { version: "1.0.7", date: "2026-06-01", notes: "Updated SMTP and admin-token configuration." },
      { version: "1.0.2", date: "2026-03-09", notes: "Initial stable package." },
    ],
  },
  {
    id: "coder",
    name: "Coder",
    summary: "Self-Hosted Cloud Development Environments.",
    category: "developer",
    developer: "青焰Hub",
    language: "EN",
    languageName: "English",
    icon: appAssetIcon("coder"),
    hero: assetPath("usecase-previz-room.webp"),
    version: "1.0.12",
    source: "Public",
    stats: { memory: "4 GB", disk: "12 GB", cpu: "4 Core", gpu: "-" },
    permissions: ["network_proxy", "dataset", "terminal_access"],
    description:
      "Launch secure cloud development workspaces close to your private data and internal services.",
    screenshots: [assetPath("usecase-previz-room.webp")],
    versions: [
      { version: "1.0.12", date: "2026-06-26", notes: "Updated workspace templates and proxy routing." },
      { version: "1.0.6", date: "2026-04-08", notes: "Improved terminal entrance reliability." },
    ],
  },
  {
    id: "langbot",
    name: "LangBot",
    summary: "Production-grade platform for building agentic IM bots",
    category: "ai",
    developer: "青焰Hub",
    language: "EN",
    languageName: "English",
    icon: appAssetIcon("langbot", "png"),
    hero: assetPath("usecase-ad-storyboard.webp"),
    version: "1.0.7",
    source: "Public",
    stats: { memory: "-", disk: "-", cpu: "-", gpu: "-" },
    permissions: ["drive_file_move", "network_proxy", "user_profile"],
    description:
      "Connect model backends to messaging channels and build production-grade conversational agents.",
    screenshots: [assetPath("usecase-ad-storyboard.webp")],
    versions: [
      { version: "1.0.7", date: "2026-06-20", notes: "Updated channel connectors and app permissions." },
      { version: "1.0.2", date: "2026-04-02", notes: "Initial marketplace release." },
    ],
  },
];

export const marketSections = [
  { id: "community", titleKey: "communityChoices", apps: ["ollama", "openwebui", "openclaw", "comfyui", "steamheadless"] },
  { id: "top", titleKey: "topApps", apps: ["affine", "nocodb", "n8n", "bytebase", "jellyfin"] },
  { id: "latest", titleKey: "latestApps", apps: ["openclaw", "n8n", "coder", "ollama", "vaultwarden", "langbot"] },
];

export const getAppById = (id) =>
  marketApps.find((app) => app.id === id) ?? marketApps[0];

export const getAppsByIds = (ids) =>
  ids.map((id) => getAppById(id)).filter(Boolean);

export const getCategoryLabel = (categoryId, locale = "zh") =>
  appCategories.find((item) => item.id === categoryId)?.label?.[locale] ||
  appCategories.find((item) => item.id === categoryId)?.label?.zh ||
  categoryId;

export const tAppMarket = (locale, key) =>
  (appMarketCopy[locale] || appMarketCopy.zh)[key] || appMarketCopy.zh[key] || key;
