const assetPath = (name) => `${import.meta.env.BASE_URL}assets/${name}`;
const appAssetIcon = (name, extension = "svg") =>
  assetPath(`app-icons/${name}.${extension}`);

export const appCategories = [
  { id: "discover", label: { zh: "发现", en: "Discover" }, icon: "radar" },
  { id: "creativity", label: { zh: "创作", en: "Creativity" }, icon: "draw" },
  { id: "productivity", label: { zh: "效率", en: "Productivity" }, icon: "work" },
  { id: "developer", label: { zh: "开发工具", en: "Developer Tools" }, icon: "terminal" },
  { id: "fun", label: { zh: "娱乐", en: "Fun" }, icon: "spark" },
  { id: "lifestyle", label: { zh: "生活方式", en: "Lifestyle" }, icon: "leaf" },
  { id: "utilities", label: { zh: "实用工具", en: "Utilities" }, icon: "extension" },
  { id: "ai", label: { zh: "AI", en: "AI" }, icon: "brain" },
];

export const appMarketCopy = {
  zh: {
    brand: "应用市场",
    marketKicker: "VerdantFlare Public App Catalog",
    marketTitle: "应用市场",
    marketLead:
      "发现适合你的创作工具，了解版本与运行要求。在 Hub 查看授权，通过 Studio 安装到当前 Station。",
    recommended: "查看推荐应用",
    orbitLabel: "应用市场摘要",
    orbitMeta: "已发布应用 · 版本与资源要求",
    search: "搜索",
    categories: "分类",
    category: "分类",
    allCategories: "全部分类",
    view: "展示",
    viewAria: "切换展示方式",
    grid: "图块",
    list: "列表",
    quickFilter: "应用分类快捷筛选",
    all: "全部",
    loadMore: "加载更多应用",
    allShown: "已展示全部",
    appsUnit: "个应用",
    discover: "发现",
    amazingApps: "发现精彩应用",
    searchPlaceholder: "搜索应用、分类或描述",
    communityChoices: "社区精选",
    topApps: "青焰热门应用",
    latestApps: "最新应用",
    seeAll: "查看全部",
    back: "返回应用市场",
    catalogVersion: "当前目录版本",
    referenceMemory: "参考内存",
    referenceDisk: "参考磁盘",
    referenceCpu: "参考 CPU",
    referenceGpu: "参考 GPU",
    publicListingDisclaimer: "此页仅为公开目录资料，不代表应用已在 Station 安装或可运行。",
    accessInHub: "前往 Hub 查看组织权益",
    originalChinese: "以下资料保留原始中文；英文译文尚未审核。",
    catalogLoading: "正在加载公开应用目录…",
    catalogError: "公开目录暂不可用：",
    catalogEmpty: "暂无已公开应用；请稍后查看。",
    developer: "开发者",
    languageLabel: "语言",
    memory: "所需内存",
    disk: "所需磁盘",
    cpu: "所需 CPU",
    gpu: "所需 GPU",
    about: "应用介绍",
    screenshots: "应用截图",
    chartVersion: "Chart 版本",
    versionHistory: "当前版本",
    seeAllVersions: "查看所有版本",
    sourceCode: "源代码",
    public: "公开",
    requiredPermissions: "所需权限",
    get: "前往 Hub",
    install: "在 Hub 开通",
    compatible: "兼容青焰应用协议",
    versionHistoryTitle: "版本历史",
    released: "发布时间",
    changelog: "更新内容",
    current: "当前版本",
    allVersions: "全部版本",
  },
  en: {
    brand: "VerdantFlare Market",
    marketKicker: "VerdantFlare Public App Catalog",
    marketTitle: "App Market",
    marketLead:
      "Find your next creative tool and review its version and requirements. Check access in Hub, then install on your active Station through Studio.",
    recommended: "View Recommended App",
    orbitLabel: "App market summary",
    orbitMeta: "Published apps · Versions and requirements",
    search: "Search",
    categories: "Categories",
    category: "Category",
    allCategories: "All Categories",
    view: "View",
    viewAria: "Switch display mode",
    grid: "Grid",
    list: "List",
    quickFilter: "App category quick filters",
    all: "All",
    loadMore: "Load More Apps",
    allShown: "Showing all",
    appsUnit: "apps",
    discover: "Discover",
    amazingApps: "Discover Amazing Apps",
    searchPlaceholder: "Search apps, categories, or descriptions",
    communityChoices: "Community choices",
    topApps: "Top apps on verdantflare",
    latestApps: "Latest apps on verdantflare",
    seeAll: "See all",
    back: "Back to Market",
    catalogVersion: "Current catalog version",
    referenceMemory: "Reference memory",
    referenceDisk: "Reference disk",
    referenceCpu: "Reference CPU",
    referenceGpu: "Reference GPU",
    publicListingDisclaimer: "This public listing does not mean the app is installed or ready to run on your Station.",
    accessInHub: "Check organization access in Hub",
    originalChinese: "The following catalog details remain in their original Chinese; an English translation has not been reviewed.",
    catalogLoading: "Loading the public app catalog…",
    catalogError: "The public catalog is temporarily unavailable. Please try again later.",
    catalogEmpty: "No public apps are available yet. Please check back later.",
    developer: "Developer",
    languageLabel: "Language",
    memory: "Required memory",
    disk: "Required disk",
    cpu: "Required CPU",
    gpu: "Required GPU",
    about: "About",
    screenshots: "Screenshots",
    chartVersion: "Chart version",
    versionHistory: "Current version",
    seeAllVersions: "See all versions",
    sourceCode: "Source code",
    public: "Public",
    requiredPermissions: "Required permissions",
    get: "Open in Hub",
    install: "Activate in Hub",
    compatible: "Compatible with verdantflare app protocol",
    versionHistoryTitle: "Version history",
    released: "Released",
    changelog: "Changelog",
    current: "Current",
    allVersions: "All versions",
  },
};

export const getCategoryLabel = (categoryId, locale = "zh") =>
  appCategories.find((item) => item.id === categoryId)?.label?.[locale] ||
  appCategories.find((item) => item.id === categoryId)?.label?.zh ||
  (locale === "en" && categoryId === "音乐创作" ? "Music creation" : "") ||
  categoryId;

export const tAppMarket = (locale, key) =>
  (appMarketCopy[locale] || appMarketCopy.zh)[key] || appMarketCopy.zh[key] || key;
